import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/context";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import "@uploadthing/react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <AuthProvider>
          <Navbar/>
          {children}
          <Toaster/>
        </AuthProvider>
      </body>
    </html>
  );
}
